### ISSUE TITLE
install wordlists in local directory instead of /usr/lib/nagaram ?

### ISSUE THREAD

**Issue by icewater** [a-tal/nagaram#7]
Is it possible to install this application with pip in a local virtualenv directory, without requiring write access to /usr/local?

**Comment by a-tal** [comment]
yep! no problem at all, I just updated the setup.py to install the wordlists with the package.

thanks for bringing this up!

**Comment by a-tal** [comment]
hmm, this is only working in py3 as of right now.

reopening to make work in 2.7 as well :(

**Comment by a-tal** [comment]
ok, some fighting with pypi and this is sorted now.

as of 0.3.8 everything should install nicely with the package source files, via source or pip.

**Comment by icewater** [comment]
Confirmed!  :-)
